config/routes.rb
Rails.application.routes.draw do
  root to: "orders#new"
  resources :orders, only: [:new, :create, :show, :index]
  namespace :admin do
    root to: "orders#index"
    resources :orders, only: [:index, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessor :input_string

  validates :number, format: {with: /\d{3}-\d{7}-\d{7}/ }, uniqueness: true
  validates :deliver_by, presence: { message: "is not formatted correctly" }
  before_validation :format_input


  def format_input
    begin
      input_array = input_string.split("\n")
      input_array = input_string.split("|") unless input_array.length > 1
      order_string = input_array[0].split("Order Number: ")[1].strip
      date_string = input_array[1].split("delivery by ")[1]
      self.number = order_string
      date_string_to_dates date_string
    rescue => ex
      errors.add(:base, "Inputted string is non-parsable")
    end
  end

  def date_string_to_dates date_string
    deliver_array = date_string.split("-")
    self.deliver_by = Chronic.parse(deliver_array[-1])
    if deliver_array.length > 1
      self.earliest_deliver = Chronic.parse(deliver_array[0])
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  #http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD']
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to admin_root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(input_string: params[:order][:input_string])
    if @order.save
      render json: @order
    else
      render json: { 
        errors: @order.errors.full_messages 
      }.to_json,
      status: 422
    end
  end

  def show
    @order = Order.find_by_number(params[:id])
    if @order
      render json: @order
    else
      render json: { 
        error: "Order not found"
      }.to_json,
      status: 404
    end
  end

  def index
    @orders = Order.all
    render json: @orders
  end

  private

  def order_params
    params.require(:order).permit(:input_string)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/orders/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Deliver By</th>
      <th scope="col">Earliest Delivery</th>
      <th scope="col"></th>
    </tr>
  <thead>
  <tbody>
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <th scope="col">
          <%= link_to order.number, "/orders/#{order.number}"%>
        </th>
        <th scope="col">
          <%= order.deliver_by %>
        </th>
        <th scope="col">
          <%= order.earliest_deliver%>
        </th>
        <th scope="col">
          <%= button_to "delete", admin_order_path(order), method: :delete, class: "btn btn-primary" %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PurseChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="container">
  <div class="row" style="margin-top: 20px;">
    <div class="col">
      <h5>
        Please enter text in following format, with a new line between order and delivery:
      </h5>
      <div style="padding: 10px; background-color: #eee; margin-bottom: 10px;">
        Order Number: 232-9384712-9823512
        <br />
        Estimated delivery by Dec. 20, 2016 - Dec. 30, 2016
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= form_for @order do |f| %>
        <div class="form-group">
          <%= f.text_area :input_string, style: "width: 100%; height: 200px;"%>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Admin", admin_root_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>